### ISSUE TITLE
Remove evil, no good, bad log statement

### ISSUE THREAD

**Issue by lawik** [electric-sql/typescript-client#75]
Not on a device to fix it so reporting it: https://github.com/electric-sql/typescript-client/blob/4e529cdb03ae9cdd6cd723e75cc156299d134452/src/notifiers/event.ts#L206

very dramatic :)

**Comment by define-null** [comment]
Hej, thanks for reporting this, it has been fixed.

**Comment by lawik** [comment]
Does this go out in some specific release version?
